apiVersion: apps/v1
kind: Deployment
metadata:
  name: vwh-debug
  namespace: default
  labels:
    app: vwh-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vwh-debug
  template:
    metadata:
      labels:
        app: vwh-debug
    spec:
      containers:
        - name: vwh-debug
          image: teochenglim/k8s-vwh-debug:latest
          imagePullPolicy: IfNotPresent
          args:
          - -tlsCertFile=/etc/webhook/certs/cert.pem
          - -tlsKeyFile=/etc/webhook/certs/key.pem
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: vwh-debug
